const nodemailer = require("nodemailer");
const { CustomError } = require("./router-utils");

async function sendMail(receiver, subject, message) {
  const emailFooter = `
    <p style="font-size: 12px; color: #999;">This email was automatically generated by Grievance Support System. Please do not reply to this email.</p>
    `;

  const fullMessage = message + emailFooter;

  let transporter = nodemailer.createTransport({
    service: "gmail",
    host: "smtp.gmail.com",
    port: 465,
    secure: true,
    auth: {
      user: "gamingzone0631@gmail.com",
      pass: "alihpjvownpuqsof",
    },
  });

  let mailOptions = {
    from: "Grievance Support System <gamingzone0631@gmail.com>",
    to: receiver,
    subject: subject,
    html: fullMessage,
  };

  try {
    const emailRes = await transporter.sendMail(mailOptions);
    console.log(emailRes);
  } catch (err) {
    throw CustomError("Failed to send mail", 400);
  }
}

async function sendMailToPersons(personArray) {
  for (let index = 0; index < personArray.length; index++) {
    const ele = personArray[index];
    const emailSubject = "Welcome to our Grievance Support System";
    const emailText = `
		Dear ${ele["email"]},<br>
		Your account has been created successfully.<br>
		<br>
		Username: ${ele.email}<br>
		Password: ${ele.password}<br>
		<br>
		`;

    await sendMail(ele["email"], emailSubject, emailText);
  }
}

module.exports = {
  sendMail,
  sendMailToPersons,
};
